### ISSUE TITLE
Sending HTTP traffic over Hyperswarm. Should we consider supporting multiplexing in the protocol?

### ISSUE THREAD

**Issue by pfrazee** [holepunchto/hyperdht#54]
Sending HTTP traffic over Hyperswarm sockets is a use-case I'm currently exploring. This leads to a small challenge:

HTTP semantics depend on the connection life-cycle. After a response is finished, the server is expected to close the connection. This seems like a problem for Hyperswarm, because connection setup isn't as quick as it is for traditional TCP. We don't want to open and close connections for every request.

One option is to use empty messages to indicate the end of a request or response, without closing the stream. This should work so long as responses are sent in the same order that requests are sent, but that's a performance penalty.

We can improve on that by using multiplexing such as in [libp2p-mplex](https://github.com/libp2p/js-libp2p-mplex). This would allow multiple in-flight HTTP request/responses, and the "channels" could be freed for reuse after the req/res sessions end on each of them.

I'm opening this issue for two reasons:

1. To confirm that I understand the situation correctly. (not a given)
2. If I'm correct, I wonder if there'd be any merit to supporting multiplexing natively in the protocol? I have two reasons for suggesting that: A) It might be useful in other contexts, and B) I suspect that sending HTTP over Hyperswarm sockets will be really common, and since Hyperswarm sockets don't have any "standard header" to declare the message format they're about to send, having multiplexing on all sockets would simplify things.

**Comment by pfrazee** [comment]
Another option I might look into is using HTTP/2, which supports multiplexing.

**Comment by mafintosh** [comment]
The hyperswarm layer will likely never support any high level protocols. Support is coming for TCP in addition to UTP and we are open to adding more "raw protocols". If you wanna run any multiplexing you should do that on top of your raw connection. The only exception to this might be a websocket interface for browser compat, but I'd prefer not doing that here as well for the same reasons. For the same reasons headers don't make much sense, it's just an encrypted raw socket.

In addition connections are always handshaked seperately through the dht for holepunching reasons.

I'd suggest the following:

* Quantify what "isn't as quick" means - it's a testnet that is clustered in europe atm - do you mean high latency? Whats the numbers? Where are you connecting to/from.
* Contribute low level benchmarks that help us track this over time

**Comment by lanmower** [comment]
My hyper-web-relay experiment deals with experimental connection maintenance, traditional proxies will keep a connection open and re-use it when set up correctly, I believe direct relaying of a browser to a web server typically accomplishes the same thing since the connection maintenance and multiplexing happens on the http layer of the protocol stack

**Comment by mafintosh** [comment]
Doesn't matter where the nodes are, I'd imagine the bulk of the current latency is speed of light to the testnet DHT which is all running in northern germany. All handshakes go through the DHT always - that's how you holepunch.

With a more widely deployed DHT this might be better or worse. For both your localities I'd imagine it can only get better as it's really far geographically to the testnet.

**Comment by mafintosh** [comment]
You should look into HTTP pipelining, it's basically multiplexing for 90% of all use cases.

**Comment by mafintosh** [comment]
Also making multiple connections to the SAME host is very optimisable (read competive to direct connections)

**Comment by mafintosh** [comment]
Just confirmed through some googling that node's http server HAS pipelining but the client doesn't. https://github.com/nodejs/undici does tho.

**Comment by pfrazee** [comment]
@lanmower I'm guessing your `hyper-web-relay` package is going to get different kinds of HTTP traffic from nginx than it would from a browser directly accessing it.

**Comment by lanmower** [comment]
That being said, all browsers multiplex.

**Comment by lanmower** [comment]
@pfrazee can you link me to where you do multiplexing? maybe I can blatantly steal your technique for hyper-web-relay :)

**Comment by pfrazee** [comment]
I ended up solving it by putting an nginx reverse proxy in front with keep-alive enabled
